logger:
  namespace: company-metrics-api

chs:
  kafka:
    api:
      endpoint: ${CHS_URL:localhost}
      key: ${CHS_API_KEY:chsApiKey}

springfox:
  documentation:
    auto-startup: false

mongodb:
  company-metrics:
    collection:
      name: ${COMPANY_METRICS_COLLECTION_NAME:company_metrics}
  charges:
    collection:
      name: ${CHARGES_CHARGES_COLLECTION_NAME:company_mortgages}
  appointments:
    collection:
      name: ${APPOINTMENTS_COLLECTION_NAME:appointments}
  psc-statements:
    collection:
      name: ${PSC_STATEMENTS_COLLECTION_NAME:company_psc_statements}
  pscs:
    collection:
      name: ${PSC_STATEMENTS_COLLECTION_NAME:company_pscs}

spring:
  jackson:
    default-property-inclusion: NON_NULL
  data:
    mongodb:
      metrics:
        uri: ${MONGODB_METRICS_URL:mongodb://mongo:27017/company_metrics}
        name: company_metrics
        collection: ${METRICS_COLLECTION_NAME:company_metrics}
      charges:
        uri: ${MONGODB_CHARGES_URL:mongodb://mongo:27017/company_mortgages}
        name: company_mortgages
        collection: ${CHARGES_COLLECTION_NAME:company_mortgages}
      appointments:
        uri: ${MONGODB_APPOINTMENTS_URL:mongodb://mongo:27017/appointments}
        name: appointments
        collection: ${APPOINTMENTS_COLLECTION_NAME:appointments}
      psc-statements:
        uri: ${MONGODB_PSC_STATEMENTS_URL:mongodb://mongo:27017/company_psc_statements}
        name: company_psc_statements
        collection: ${PSC_STATEMENTS_COLLECTION_NAME:company_psc_statements}
      pscs:
        uri: ${MONGODB_PSCS_URL:mongodb://mongo:27017/company_pscs}
        name: company_psc_statements
        collection: ${PSC_STATEMENTS_COLLECTION_NAME:company_pscs}

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /company-metrics-api
      path-mapping:
        health: healthcheck
  endpoint:
    health:
      show-details: never
      enabled: true
