logger:
  namespace: company-metrics-api

mongo:
  company-metrics-collection: company_metrics

chs:
  kafka:
    api:
      endpoint: ${CHS_URL:localhost}
      key: ${CHS_API_KEY:chsApiKey}

springfox:
  documentation:
    auto-startup: false

mongodb:
  company:
    metrics:
      transactions: ${TRANSACTIONS_ENABLED:false}

spring:
  jackson:
    default-property-inclusion: NON_NULL
  data:
    mongodb:
      metrics:
        uri: ${MONGODB_METRICS_URL:mongodb://localhost:27017/company_metrics}
        name: company_metrics
        collection: ${METRICS_COLLECTION_NAME:company_metrics}
      charges:
        uri: ${MONGODB_CHARGES_URL:mongodb://localhost:27017/company_mortgages}
        name: company_mortgages
        collection: ${CHARGES_COLLECTION_NAME:company_mortgages}

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /company-metrics-api
      path-mapping:
        health: healthcheck
  endpoint:
    health:
      show-details: never
      enabled: true