logger:
  namespace: company-metrics-api

mongo:
  company-metrics-collection: company_metrics


chs:
  kafka:
    api:
      endpoint: ${CHS_URL:localhost}
      key: ${CHS_API_KEY:chsApiKey}

springfox:
  documentation:
    auto-startup: false


mongodb:
  company:
    metrics:
    transactions: ${TRANSACTIONS_ENABLED:false}
    collection:
      name: ${COMPANY_METRICS_COLLECTION_NAME:company_metrics}


spring:
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://localhost:27017/company_metrics}
      name: company_metrics
